name: Build and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Echo IDS"
        run: echo $ORG_GRADLE_PROJECT_signingKeyId

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: publishToSonatype

      - name: Deploy javadoc to Github Pages
        uses: dev-vince/actions-publish-javadoc@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: "17"
          java-distribution: "adopt" # The distributor of the target JDK. See https://github.com/actions/setup-java for more information.
          project: gradle # The project type.
          branch: "gh-pages" # The branch for the javadoc contents.
