name: Test And Deploy

permissions:
  contents: write
  
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"
      - name: Run the Maven tests
        run: mvn test
        
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy javadoc to Github Pages
        uses: dev-vince/actions-publish-javadoc@v1.0.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            java-version: "17" # Replace with your java version. Default is 17
            java-distribution: "adopt" # The distributor of the target JDK. See https://github.com/actions/setup-java for more information. Defauly is adopt
            project: maven # The project type. By default maven
            branch: "gh-pages" # The branch for the javadoc contents. By default gh-pages
